# Generated by Django 3.2.14 on 2022-07-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='post',
            new_name='product',
        ),
    ]
