# Generated by Django 3.2.14 on 2022-07-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='postimage',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
